name: Codacy Coverage Reporter

on: ["push"]

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: Codacy Coverage Reporter
    steps:
      - uses: actions/checkout@v2
      - name: Composer (php-actions)
        uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          version: 2.x
      - name: PHPUnit (php-actions)
        uses: php-actions/phpunit@v4
        with:
          configuration: phpunit.xml
          version: "10.5"
          php_version: "8.1"
          php_extensions: "pcov"
          args: --coverage-clover phpunit-clover.xml
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: phpunit-clover.xml
